#!/usr/bin/env python3
"""
解析 AndroidManifest.xml，提取匹配指定前缀的组件名，
生成 disable.sh / enable.sh / list.sh 三个 shell 脚本，输出到 gen_shell/ 目录。
"""

import xml.parsers.expat
import os
import sys

USAGE = """用法: {script} [选项] <AndroidManifest.xml>

选项:
  -p PREFIX   组件名前缀（默认: com.tencent.mm.plugin.appbrand）
  -t TYPES    组件类型，逗号分隔: activity,service,receiver,provider（默认: activity）
  -h          显示此帮助

示例:
  {script} AndroidManifest.xml
  {script} -p com.tencent.mm.plugin.appbrand AndroidManifest.xml
  {script} -t activity,service AndroidManifest.xml
  {script} -p com.tencent.mm -t activity,service,receiver AndroidManifest.xml
"""

SHBANG = "#!/system/bin/sh"

# 合法的 Android 组件标签名 -> 显示名称
VALID_TAGS = {
    "activity": "Activity",
    "service": "Service",
    "receiver": "Receiver",
    "provider": "Provider",
}


def parse_args():
    """解析命令行参数，返回 (xml_path, prefix, tag_names)。"""
    args = sys.argv[1:]
    prefix = "com.tencent.mm.plugin.appbrand"
    tag_names = ["activity"]  # 默认只解析 activity
    xml_path = None

    i = 0
    while i < len(args):
        a = args[i]
        if a in ("-h", "--help", "/?"):
            print(USAGE.format(script=sys.argv[0]))
            sys.exit(0)
        elif a == "-p":
            i += 1
            if i >= len(args):
                print("错误：-p 缺少参数")
                sys.exit(1)
            prefix = args[i]
        elif a == "-t":
            i += 1
            if i >= len(args):
                print("错误：-t 缺少参数")
                sys.exit(1)
            raw = [x.strip().lower() for x in args[i].split(",") if x.strip()]
            invalid = [t for t in raw if t not in VALID_TAGS]
            if invalid:
                print(f"错误：不支持的组件类型 {invalid}，可选: {','.join(VALID_TAGS)}")
                sys.exit(1)
            tag_names = raw
        elif not a.startswith("-"):
            xml_path = a
        else:
            print(f"错误：未知选项 {a}")
            sys.exit(1)
        i += 1

    if xml_path is None:
        print("错误：请指定 AndroidManifest.xml 路径")
        print(USAGE.format(script=sys.argv[0]))
        sys.exit(1)

    return xml_path, prefix, tag_names


def parse_manifest(xml_path, prefix, tag_names):
    """
    解析 AndroidManifest.xml，提取：
      - 包名 (<manifest package="...">)
      - 所有 android:name 以 prefix 开头的指定标签类型
    返回 (manifest_pkg, [(tag, name), ...])
    """
    if not os.path.exists(xml_path):
        print(f"错误：文件不存在: {xml_path}")
        sys.exit(1)

    manifest_pkg = ""
    matches = []  # [(tag, full_name), ...]

    def start_element(name, attrs):
        nonlocal manifest_pkg
        if name == "manifest":
            manifest_pkg = attrs.get("package", "")
        elif name in tag_names:  # 只处理用户指定的标签类型
            val = attrs.get("android:name", attrs.get("name", ""))
            if val and val.startswith(prefix):
                matches.append((name, val))

    p = xml.parsers.expat.ParserCreate()
    p.StartElementHandler = start_element

    with open(xml_path, "rb") as f:
        try:
            p.ParseFile(f)
        except xml.parsers.expat.ExpatError as e:
            print(f"错误：XML 解析失败 -> {e}")
            sys.exit(1)

    if not manifest_pkg:
        print("错误：无法从 <manifest> 标签中获取包名")
        sys.exit(1)

    if not matches:
        types_str = ",".join(tag_names)
        print(f"未找到前缀为 '{prefix}' 的 {types_str}")
        sys.exit(0)

    return manifest_pkg, matches


def out_dir():
    """返回脚本所在目录下的 out/ 路径，自动创建。"""
    script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
    d = os.path.join(script_dir, "out")
    os.makedirs(d, exist_ok=True)
    return d


def filename(action, tag_names, prefix):
    """生成文件名: {action}_{types}_{prefix}.sh"""
    types_part = "+".join(tag_names)
    return f"{action}_{types_part}_{prefix}.sh"


def gen_disable(outdir, manifest_pkg, matches, label, tag_names, prefix):
    lines = [
        SHBANG,
        f"# Generated by gen_scripts.py -- disable all {label}",
        "",
    ]
    for tag, name in matches:
        comp = f"{manifest_pkg}/{name}"
        lines.append(f"pm disable \"{comp}\"")

    path = os.path.join(outdir, filename("disable", tag_names, prefix))
    text = "\n".join(lines) + "\n"
    with open(path, "w", newline="") as f:
        f.write(text)
    os.chmod(path, 0o755)
    print(f"  -> {path}")


def gen_enable(outdir, manifest_pkg, matches, label, tag_names, prefix):
    lines = [
        SHBANG,
        f"# Generated by gen_scripts.py -- enable all {label}",
        "",
    ]
    for tag, name in matches:
        comp = f"{manifest_pkg}/{name}"
        lines.append(f"pm enable \"{comp}\"")

    path = os.path.join(outdir, filename("enable", tag_names, prefix))
    text = "\n".join(lines) + "\n"
    with open(path, "w", newline="") as f:
        f.write(text)
    os.chmod(path, 0o755)
    print(f"  -> {path}")


def gen_list(outdir, manifest_pkg, matches, label, tag_names, prefix):
    components = [f"{manifest_pkg}/{name}" for _, name in matches]

    lines = [
        SHBANG,
        f"# Generated by gen_scripts.py -- list status of all {label}",
        "",
        f'PKG="{manifest_pkg}"',
        'DUMP=$(dumpsys package "$PKG" 2>/dev/null)',
        "",
        'echo "=== Component Status ($PKG) ===="',
        "echo",
    ]

    for comp in components:
        cls = comp.split("/", 1)[1]
        lines.append(
            f'state=$(echo "$DUMP" | grep -F "{cls}" | grep -oE "enabled=[a-z]*|status=[a-z]*" | head -1)'
        )
        lines.append(f'case "$state" in')
        lines.append(f'  "enabled=true"|"status=enabled")   echo "ENABLED  {comp}" ;;')
        lines.append(f'  "enabled=false"|"status=disabled") echo "DISABLED {comp}" ;;')
        lines.append(f'  *)                                  echo "UNKNOWN  {comp}" ;;')
        lines.append(f'esac')
        lines.append("")

    path = os.path.join(outdir, filename("list", tag_names, prefix))
    text = "\n".join(lines) + "\n"
    with open(path, "w", newline="") as f:
        f.write(text)
    os.chmod(path, 0o755)
    print(f"  -> {path}")


def main():
    xml_path, prefix, tag_names = parse_args()

    # 解析 XML
    manifest_pkg, matches = parse_manifest(xml_path, prefix, tag_names)

    # 按标签类型统计
    type_counts = {}
    for tag, name in matches:
        type_counts[tag] = type_counts.get(tag, 0) + 1

    print(f"包名: {manifest_pkg}")
    print(f"前缀: {prefix}")
    print(f"组件类型: {', '.join(tag_names)}")
    print(f"匹配到 {len(matches)} 个组件:")
    for tag, name in matches:
        print(f"  [{tag}] {name}")
    print()

    # 构造描述标签（用于脚本注释）
    type_labels = [f"{n} {VALID_TAGS[t]}" for t in tag_names for n in [type_counts.get(t, 0)]]
    label = f"{len(matches)} components ({', '.join(f'{type_counts[t]} {VALID_TAGS[t].lower()}s' for t in tag_names)})"

    outdir = out_dir()
    print(f"输出目录: {outdir}")
    print("正在生成脚本...")

    gen_disable(outdir, manifest_pkg, matches, label, tag_names, prefix)
    gen_enable(outdir, manifest_pkg, matches, label, tag_names, prefix)
    gen_list(outdir, manifest_pkg, matches, label, tag_names, prefix)

    print("完成。")


if __name__ == "__main__":
    main()
